CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY,
    SURNAME CHAR(25) NOT NULL,
    NAME CHAR(25) NOT NULL,
    ADDRESS CHAR(250),
    EMAIL CHAR(25)
);

CREATE TABLE STUFF (
    ID INT PRIMARY KEY,
    NAME CHAR(100) NOT NULL,
    PRICE FLOAT NOT NULL,
    CAT_NUMBER INT
);

CREATE TABLE ORDERS (
    ID INT PRIMARY KEY,
    Data DATE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    STUFF_ID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK (Ilość > 0),
    VALUE FLOAT NOT NULL CHECK (Wartość >= 0),
    STATUS INT NOT NULL,
    
    CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDERS_STUFF FOREIGN KEY (STUFF_ID) REFERENCES STUFF(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_STUFF ON ORDERS(STUFF_ID);
